### ISSUE TITLE
Workshop item downloading?

### ISSUE THREAD

**Issue by gameboycjp** [Jackzmc/rs-steam-workshop-api#1]
Is it possible to download mods from the workshop with this library?

**Comment by Jackzmc** [comment]
Not with this library directly, but it can expose a file url from workshop items in some games that you can download from. An example is from my workshop download tool for L4D2: https://github.com/Jackzmc/l4d2-workshop-downloader (it is broken I believe tho).

For other, newer games you'll have to just use steamcmd
